### ISSUE TITLE
Any interest in a uvec method?

### ISSUE THREAD

**Issue by m-wells** [oschulz/UnsafeArrays.jl#6]
Is there any interest in a `uvec` method?  I imagine it would be something like 
```julia
uvec(x::AbstractArray) = uview(x, eachindex(x))
```

**Comment by oschulz** [comment]
You can already call `vec` on an `UnsafeArray`:

```julia
using UnsafeArrays
A = rand(4, 6)
@uviews A begin
    va = vec(A)
    va isa UnsafeArray{Float64,1}
end
```

So I don't think we need a special `uvec` function. Also, in general, `uview` should rarely be used directly - use the `@uviews` macro instead, it protectd the original arrays from GC.

**Comment by oschulz** [comment]
If you had something more specialized in mind, though, please feel free to reopen this issue, @m-wells!
